#!/usr/bin/php -q

<?php

if(!defined("STDIN")) {
    define("STDIN", fopen('php://stdin','r'));
}

exec('clear');

echo "\n*****\n\nLightningSkript\n\n*****\n\n";

sleep(2);

echo "Which LightningSkript package would you like to install? (enter below)\n";
$packageToInstall = fread(STDIN, 80);

echo "\n" . 'Searching for package "' . $packageToInstall . '" in LSkript database...' . "\n\n";

sleep(2);



function install($programpre) {

        $program = str_replace(array("\n", "\r"), '', $programpre);

        echo 'Attempting to Install "' . $program . '"';

        exec('brew install ' . $program . ' >/dev/null 2>/dev/null', $output, $return);

        if (!$return) {
            echo "\n\n\n" . '[SUCCESS] "' . $program . '" Installed' . "\n\n\n";
        } else {
            echo "\n\n" . '[ERROR] "' . $program . '" Installation Failed' . "\n\n";
        }

    }

        function does_url_exist($url) {
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_NOBODY, true);
            curl_exec($ch);
            $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            if ($code == 200) {
                $status = true;
            } else {
                $status = false;
            }

            curl_close($ch);
            return $status;
        }

        if ( does_url_exist('https://raw.githubusercontent.com/LSkript/LSkript/main/skripts/' . $packageToInstall . '.php') == true ) {

            exec('sudo wget https://raw.githubusercontent.com/LSkript/LSkript/main/skripts/' . $packageToInstall . '.php -P ~/LSkript');
            include(exec('echo ~') . '/LSkript/' . $_SERVER["argv"][1] . '.php');
            echo "\n" . 'Complete!' . "\n";

        }

